-- DDL PostgreSQL
-- Modelo: Reservas deportivas / Escuela Militar
-- Esquemas: ms1_nucleo, ms2_verificacion, ms3_inventario, ms5_quejas

CREATE SCHEMA IF NOT EXISTS ms1_nucleo;
CREATE SCHEMA IF NOT EXISTS ms2_verificacion;
CREATE SCHEMA IF NOT EXISTS ms3_inventario;
CREATE SCHEMA IF NOT EXISTS ms5_quejas;

-- ============================================================
-- MS2 - VERIFICACION
-- ============================================================

CREATE TABLE ms2_verificacion.tipo_cuenta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ms2_verificacion.rol (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo_cuenta_id INTEGER NOT NULL
);

CREATE TABLE ms2_verificacion.permiso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

CREATE TABLE ms2_verificacion.rol_permiso (
    rol_id INTEGER NOT NULL,
    permiso_id INTEGER NOT NULL,
    PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE ms2_verificacion.usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cuenta_id INTEGER NOT NULL,
    rol_id INTEGER NOT NULL,
    nombre_usuario VARCHAR(100) NOT NULL UNIQUE,
    alias VARCHAR(100),
    hash_password VARCHAR(255) NOT NULL,
    prioridad INTEGER,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ms2_verificacion.usuario_area (
    usuario_id INTEGER NOT NULL,
    tipo_espacio_id INTEGER NOT NULL,
    PRIMARY KEY (usuario_id, tipo_espacio_id)
);

CREATE TABLE ms2_verificacion.registro_acceso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_evento VARCHAR(100) NOT NULL,
    exito BOOLEAN NOT NULL
);

CREATE TABLE ms2_verificacion.sesion_activa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    expiracion TIMESTAMP NOT NULL,
    revocada BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================================
-- MS1 - NUCLEO
-- ============================================================

CREATE TABLE ms1_nucleo.tipo_espacio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo_padre_id INTEGER
);

CREATE TABLE ms1_nucleo.espacio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    tipo_espacio_id INTEGER NOT NULL,
    encargado_usuario_id INTEGER,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ms1_nucleo.convenio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_externa VARCHAR(150) NOT NULL,
    tipo_convenio VARCHAR(100) NOT NULL,
    vigente_desde DATE,
    vigente_hasta DATE
);

CREATE TABLE ms1_nucleo.reserva (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    espacio_preferido_id INTEGER,
    espacio_asignado_id INTEGER,
    solicitante_usuario_id INTEGER NOT NULL,
    remitente_usuario_id INTEGER,
    resolutor_usuario_id INTEGER,
    convenio_id INTEGER,
    estado VARCHAR(50) NOT NULL,
    orden_llegada INTEGER,
    nota_resolucion VARCHAR(500),
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ms1_nucleo.historial_reserva (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id INTEGER NOT NULL,
    estado_anterior VARCHAR(50),
    estado_nuevo VARCHAR(50) NOT NULL,
    usuario_id INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ms1_nucleo.horario_mantenimiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    espacio_id INTEGER NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    motivo VARCHAR(255) NOT NULL
);

CREATE TABLE ms1_nucleo.convenio_espacio (
    convenio_id INTEGER NOT NULL,
    espacio_id INTEGER NOT NULL,
    PRIMARY KEY (convenio_id, espacio_id)
);

CREATE TABLE ms1_nucleo.bloque_convenio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    convenio_id INTEGER NOT NULL,
    espacio_id INTEGER NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    modificable_default BOOLEAN NOT NULL DEFAULT FALSE,
    modificado_por_usuario_id INTEGER
);

CREATE TABLE ms1_nucleo.parametro_sistema (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ms1_nucleo.notificacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================================
-- MS3 - INVENTARIO
-- ============================================================

CREATE TABLE ms3_inventario.tipo_consumible (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    umbral_alerta INTEGER NOT NULL
);

CREATE TABLE ms3_inventario.inventario_espacio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    espacio_id INTEGER NOT NULL,
    tipo_consumible_id INTEGER NOT NULL,
    saldo_disponible INTEGER NOT NULL DEFAULT 0,
    UNIQUE (espacio_id, tipo_consumible_id)
);

CREATE TABLE ms3_inventario.movimiento_inventario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventario_espacio_id INTEGER NOT NULL,
    tipo_movimiento VARCHAR(50) NOT NULL,
    cantidad INTEGER NOT NULL,
    responsable_usuario_id INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- MS5 - QUEJAS / ESTADISTICAS
-- ============================================================

CREATE TABLE ms5_quejas.sugerencia_reclamo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    contenido TEXT NOT NULL,
    estado VARCHAR(50) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- FOREIGN KEYS
-- Se agregan al final para permitir referencias cruzadas
-- entre los esquemas MS1 y MS2.
-- ============================================================

-- MS2
ALTER TABLE ms2_verificacion.rol
    ADD CONSTRAINT fk_rol_tipo_cuenta
    FOREIGN KEY (tipo_cuenta_id)
    REFERENCES ms2_verificacion.tipo_cuenta(id);

ALTER TABLE ms2_verificacion.rol_permiso
    ADD CONSTRAINT fk_rol_permiso_rol
    FOREIGN KEY (rol_id)
    REFERENCES ms2_verificacion.rol(id);

ALTER TABLE ms2_verificacion.rol_permiso
    ADD CONSTRAINT fk_rol_permiso_permiso
    FOREIGN KEY (permiso_id)
    REFERENCES ms2_verificacion.permiso(id);

ALTER TABLE ms2_verificacion.usuario
    ADD CONSTRAINT fk_usuario_tipo_cuenta
    FOREIGN KEY (tipo_cuenta_id)
    REFERENCES ms2_verificacion.tipo_cuenta(id);

ALTER TABLE ms2_verificacion.usuario
    ADD CONSTRAINT fk_usuario_rol
    FOREIGN KEY (rol_id)
    REFERENCES ms2_verificacion.rol(id);

ALTER TABLE ms2_verificacion.usuario_area
    ADD CONSTRAINT fk_usuario_area_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms2_verificacion.usuario_area
    ADD CONSTRAINT fk_usuario_area_tipo_espacio
    FOREIGN KEY (tipo_espacio_id)
    REFERENCES ms1_nucleo.tipo_espacio(id);

ALTER TABLE ms2_verificacion.registro_acceso
    ADD CONSTRAINT fk_registro_acceso_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms2_verificacion.sesion_activa
    ADD CONSTRAINT fk_sesion_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

-- MS1
ALTER TABLE ms1_nucleo.tipo_espacio
    ADD CONSTRAINT fk_tipo_espacio_padre
    FOREIGN KEY (tipo_padre_id)
    REFERENCES ms1_nucleo.tipo_espacio(id);

ALTER TABLE ms1_nucleo.espacio
    ADD CONSTRAINT fk_espacio_tipo
    FOREIGN KEY (tipo_espacio_id)
    REFERENCES ms1_nucleo.tipo_espacio(id);

ALTER TABLE ms1_nucleo.espacio
    ADD CONSTRAINT fk_espacio_encargado
    FOREIGN KEY (encargado_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_espacio_preferido
    FOREIGN KEY (espacio_preferido_id)
    REFERENCES ms1_nucleo.espacio(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_espacio_asignado
    FOREIGN KEY (espacio_asignado_id)
    REFERENCES ms1_nucleo.espacio(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_solicitante
    FOREIGN KEY (solicitante_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_remitente
    FOREIGN KEY (remitente_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_resolutor
    FOREIGN KEY (resolutor_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.reserva
    ADD CONSTRAINT fk_reserva_convenio
    FOREIGN KEY (convenio_id)
    REFERENCES ms1_nucleo.convenio(id);

ALTER TABLE ms1_nucleo.historial_reserva
    ADD CONSTRAINT fk_historial_reserva
    FOREIGN KEY (reserva_id)
    REFERENCES ms1_nucleo.reserva(id);

ALTER TABLE ms1_nucleo.historial_reserva
    ADD CONSTRAINT fk_historial_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.horario_mantenimiento
    ADD CONSTRAINT fk_mantenimiento_espacio
    FOREIGN KEY (espacio_id)
    REFERENCES ms1_nucleo.espacio(id);

ALTER TABLE ms1_nucleo.convenio_espacio
    ADD CONSTRAINT fk_convenio_espacio_convenio
    FOREIGN KEY (convenio_id)
    REFERENCES ms1_nucleo.convenio(id);

ALTER TABLE ms1_nucleo.convenio_espacio
    ADD CONSTRAINT fk_convenio_espacio_espacio
    FOREIGN KEY (espacio_id)
    REFERENCES ms1_nucleo.espacio(id);

ALTER TABLE ms1_nucleo.bloque_convenio
    ADD CONSTRAINT fk_bloque_convenio_espacio
    FOREIGN KEY (convenio_id, espacio_id)
    REFERENCES ms1_nucleo.convenio_espacio(convenio_id, espacio_id);

ALTER TABLE ms1_nucleo.bloque_convenio
    ADD CONSTRAINT fk_bloque_modificado_por
    FOREIGN KEY (modificado_por_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

ALTER TABLE ms1_nucleo.notificacion
    ADD CONSTRAINT fk_notificacion_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

-- MS3
ALTER TABLE ms3_inventario.inventario_espacio
    ADD CONSTRAINT fk_inventario_espacio
    FOREIGN KEY (espacio_id)
    REFERENCES ms1_nucleo.espacio(id);

ALTER TABLE ms3_inventario.inventario_espacio
    ADD CONSTRAINT fk_inventario_tipo_consumible
    FOREIGN KEY (tipo_consumible_id)
    REFERENCES ms3_inventario.tipo_consumible(id);

ALTER TABLE ms3_inventario.movimiento_inventario
    ADD CONSTRAINT fk_movimiento_inventario
    FOREIGN KEY (inventario_espacio_id)
    REFERENCES ms3_inventario.inventario_espacio(id);

ALTER TABLE ms3_inventario.movimiento_inventario
    ADD CONSTRAINT fk_movimiento_responsable
    FOREIGN KEY (responsable_usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

-- MS5
ALTER TABLE ms5_quejas.sugerencia_reclamo
    ADD CONSTRAINT fk_sugerencia_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES ms2_verificacion.usuario(id);

-- ============================================================
-- INDICES UTILES
-- ============================================================

CREATE INDEX idx_reserva_fecha_solicitud
    ON ms1_nucleo.reserva(fecha_solicitud);

CREATE INDEX idx_reserva_estado
    ON ms1_nucleo.reserva(estado);

CREATE INDEX idx_historial_reserva
    ON ms1_nucleo.historial_reserva(reserva_id);

CREATE INDEX idx_mantenimiento_espacio
    ON ms1_nucleo.horario_mantenimiento(espacio_id);

CREATE INDEX idx_registro_acceso_usuario
    ON ms2_verificacion.registro_acceso(usuario_id);

CREATE INDEX idx_sesion_usuario
    ON ms2_verificacion.sesion_activa(usuario_id);

CREATE INDEX idx_movimiento_fecha
    ON ms3_inventario.movimiento_inventario(fecha);

CREATE INDEX idx_sugerencia_estado
    ON ms5_quejas.sugerencia_reclamo(estado);

